# Uncomment this line to define a global platform for your project
platform :ios, '10.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'TabbarWithSideMenu' do

pod 'RAMAnimatedTabBarController'
# RAMAnimatedTabBarController is used for animated tabbar view controller with different type of animation.
# Reference: https://github.com/Ramotion/animated-tab-bar

pod 'SlideMenuControllerSwift'
# SlideMenuControllerSwift is used for Side menu for left and right side.
# Reference: https://github.com/dekatotoro/SlideMenuControllerSwift/tree/swift4
end
